Maybe obj-y instead?
For whatever reason arch/efi/kernel/ isn't getting built, and so we get:

ld: arch/x86/platform/efi/efi.o: in function `efi_start_bs_thread':
efi.c:(.init.text+0xcc5): undefined reference to `efi_bs_init'